# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=100, verbose_name='CPF')),
                ('telefone', models.CharField(max_length=100, verbose_name='Telefone')),
                ('celular', models.CharField(max_length=100, verbose_name='Celular')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereço')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('dentista', models.CharField(max_length=100, verbose_name='Dentista')),
                ('valor', models.CharField(max_length=100, verbose_name='Valor Procedimento')),
                ('formaPagamento', models.CharField(max_length=100, verbose_name='Forma de Pagamento')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Data de Inicio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em ')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em ')),
            ],
        ),
    ]
